{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from glob import glob"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "filenames = glob('Combined_*[a,b,c,d,e,f,g,h,i,j,k]*160c.dta')\n",
    "list_dfs  = [pd.read_stata(f) for f in filenames]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "waves_jbhr_index = [list_dfs[i].filter(regex='jbhrcpr$').columns for i in range(11)] #This finds the index for the string 'jbhrcpr' in all waves\n",
    "waves_jbhr = [list_dfs[i][waves_jbhr_index[i]] for i in range(11)] #waves_jbhr[0-10] are now created (waves1-11)\n",
    "waves_sex_index = [list_dfs[i].filter(regex='hgsex$').columns for i in range(11)] #Finds the index for sex in each dataset\n",
    "waves_sex = [list_dfs[i][waves_sex_index[i]] for i in range(11)] #waves_sex[0-10] are now created (waves1-11)\n",
    "\n",
    "waves_employed_index = [list_dfs[i].filter(regex='esbrd$').columns for i in range(11)] #\n",
    "waves_employed = [list_dfs[i][waves_employed_index[i]] for i in range(11)] #waves_employed[0-10] are now created (waves1-11)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 348,
   "metadata": {},
   "outputs": [],
   "source": [
    "waves_join = [waves_jbhr[i].join([waves_sex[i],waves_employed[i]]) for i in range(11)] #This joins the columns of jbhr and sex for each data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 342,
   "metadata": {},
   "outputs": [],
   "source": [
    "total = [waves[i].sum(axis=1) for i in range(11)]\n",
    "total_df = [pd.DataFrame(total[i]) for i in range(11)]\n",
    "total_combine = [total_df[i].join(waves[i]) for i in range(11)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 345,
   "metadata": {},
   "outputs": [],
   "source": [
    "waves_excluded = [waves_join[i][waves_join[i].iloc[:,2] == '[1] Employed'] for i in range(11)]\n",
    "waves_excluded = [waves_excluded[i].iloc[:,:2] for i in range(11)]\n",
    "waves = [waves_excluded[i].groupby([waves_excluded[i].iloc[:,0],waves_excluded[i].iloc[:,1]]).size().unstack() for i in range(11)]\n",
    "waves = [waves[i].T for i in range(11)]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 346,
   "metadata": {},
   "outputs": [],
   "source": [
    "total = [waves[i].sum(axis=1) for i in range(11)]\n",
    "total_df = [pd.DataFrame(total[i]) for i in range(11)]\n",
    "total_combine = [total_df[i].join(waves[i]) for i in range(11)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 347,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "frac_waves = [waves[i].div(waves[i].sum(axis=1), axis=0) * 100 for i in range(11)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 228,
   "metadata": {},
   "outputs": [],
   "source": [
    "total_combine = [total_df[i].join(frac_waves[i]) for i in range(11)]\n",
    "total_combine = [total_combine[i].rename(columns={0:'Total Employed'}) for i in range(11)]\n",
    "total_combine = [total_combine[i].fillna(0) for i in range(11)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 229,
   "metadata": {},
   "outputs": [],
   "source": [
    "final_table = total_combine[0].merge(total_combine[1], how = 'outer')\n",
    "final_table = final_table.merge(total_combine[2], how = 'outer')\n",
    "final_table = final_table.merge(total_combine[3], how = 'outer')\n",
    "final_table = final_table.merge(total_combine[4], how = 'outer')\n",
    "final_table = final_table.merge(total_combine[5], how = 'outer')\n",
    "final_table = final_table.merge(total_combine[6], how = 'outer')\n",
    "final_table = final_table.merge(total_combine[7], how = 'outer')\n",
    "final_table = final_table.merge(total_combine[8], how = 'outer')\n",
    "final_table = final_table.merge(total_combine[9], how = 'outer')\n",
    "final_table = final_table.merge(total_combine[10], how = 'outer')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 230,
   "metadata": {},
   "outputs": [],
   "source": [
    "final_table = final_table.fillna('')\n",
    "row_list = final_table.index\n",
    "num_rows = len(row_list)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 231,
   "metadata": {},
   "outputs": [],
   "source": [
    "new_rows = []\n",
    "for i in range(num_rows):\n",
    "    if i == 0 or i %2 == 0:\n",
    "        new_rows.append('Male')\n",
    "    else:\n",
    "        new_rows.append('Female')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 232,
   "metadata": {},
   "outputs": [],
   "source": [
    "waves = []\n",
    "for i in range(1,12):\n",
    "    if i == 0 or i %2 == 0:\n",
    "        waves.append('Wave {}'.format(i))\n",
    "        waves.append('Wave {}'.format(i))\n",
    "    else:\n",
    "        waves.append('Wave {}'.format(i))\n",
    "        waves.append('Wave {}'.format(i))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 293,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "final_rows = [waves[i] + ' ' + new_rows[i] for i in range(22)]\n",
    "final_table.index = new_rows"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 286,
   "metadata": {},
   "outputs": [],
   "source": [
    "a = 0\n",
    "b = 2\n",
    "final_locs = []\n",
    "while a < 21:\n",
    "    final_locs.append(final_table.iloc[a:b,:])\n",
    "    a = a + 2\n",
    "    b = b + 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 296,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Total Employed</th>\n",
       "      <th>[-4] Refused/Not stated</th>\n",
       "      <th>[-3] Dont know</th>\n",
       "      <th>[1] Fewer hours</th>\n",
       "      <th>[2] About the same</th>\n",
       "      <th>[3] More hours</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>Male</td>\n",
       "      <td>4549</td>\n",
       "      <td>0.0219829</td>\n",
       "      <td>0.285777</td>\n",
       "      <td>30.160475</td>\n",
       "      <td>54.297648</td>\n",
       "      <td>15.234117</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Female</td>\n",
       "      <td>3976</td>\n",
       "      <td>0.0754527</td>\n",
       "      <td>0.301811</td>\n",
       "      <td>26.685111</td>\n",
       "      <td>55.709256</td>\n",
       "      <td>17.228370</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        Total Employed [-4] Refused/Not stated  [-3] Dont know  \\\n",
       "Male              4549               0.0219829        0.285777   \n",
       "Female            3976               0.0754527        0.301811   \n",
       "\n",
       "        [1] Fewer hours  [2] About the same  [3] More hours  \n",
       "Male          30.160475           54.297648       15.234117  \n",
       "Female        26.685111           55.709256       17.228370  "
      ]
     },
     "execution_count": 296,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "final_locs[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 304,
   "metadata": {},
   "outputs": [],
   "source": [
    "final_table = final_table.reset_index()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 306,
   "metadata": {},
   "outputs": [],
   "source": [
    "waves = []\n",
    "for i in range(1,12):\n",
    "    if i == 0 or i %2 == 0:\n",
    "        waves.append('Wave {}'.format(i))\n",
    "        waves.append('Wave {}'.format(i))\n",
    "    else:\n",
    "        waves.append('Wave {}'.format(i))\n",
    "        waves.append('Wave {}'.format(i))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 319,
   "metadata": {},
   "outputs": [],
   "source": [
    "final_table.index = waves\n",
    "final_table = final_table.rename(columns={'index':'Sex'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 326,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Sex</th>\n",
       "      <th>Total Employed</th>\n",
       "      <th>[-4] Refused/Not stated</th>\n",
       "      <th>[-3] Dont know</th>\n",
       "      <th>[1] Fewer hours</th>\n",
       "      <th>[2] About the same</th>\n",
       "      <th>[3] More hours</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <td>Wave 1</td>\n",
       "      <td>Male</td>\n",
       "      <td>4549</td>\n",
       "      <td>0.0219829</td>\n",
       "      <td>0.285777</td>\n",
       "      <td>30.160475</td>\n",
       "      <td>54.297648</td>\n",
       "      <td>15.234117</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 1</td>\n",
       "      <td>Female</td>\n",
       "      <td>3976</td>\n",
       "      <td>0.0754527</td>\n",
       "      <td>0.301811</td>\n",
       "      <td>26.685111</td>\n",
       "      <td>55.709256</td>\n",
       "      <td>17.228370</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 2</td>\n",
       "      <td>Male</td>\n",
       "      <td>4325</td>\n",
       "      <td></td>\n",
       "      <td>0.138728</td>\n",
       "      <td>31.283237</td>\n",
       "      <td>53.502890</td>\n",
       "      <td>15.075145</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 2</td>\n",
       "      <td>Female</td>\n",
       "      <td>3763</td>\n",
       "      <td></td>\n",
       "      <td>0.186022</td>\n",
       "      <td>24.608026</td>\n",
       "      <td>57.560457</td>\n",
       "      <td>17.645496</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 3</td>\n",
       "      <td>Male</td>\n",
       "      <td>4247</td>\n",
       "      <td></td>\n",
       "      <td>0.211914</td>\n",
       "      <td>31.316223</td>\n",
       "      <td>54.744526</td>\n",
       "      <td>13.727337</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 3</td>\n",
       "      <td>Female</td>\n",
       "      <td>3744</td>\n",
       "      <td></td>\n",
       "      <td>0.293803</td>\n",
       "      <td>25.240385</td>\n",
       "      <td>57.104701</td>\n",
       "      <td>17.361111</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 4</td>\n",
       "      <td>Male</td>\n",
       "      <td>4155</td>\n",
       "      <td>0.0240674</td>\n",
       "      <td>0.264741</td>\n",
       "      <td>30.878460</td>\n",
       "      <td>55.547533</td>\n",
       "      <td>13.285199</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 4</td>\n",
       "      <td>Female</td>\n",
       "      <td>3667</td>\n",
       "      <td>0</td>\n",
       "      <td>0.054540</td>\n",
       "      <td>25.934006</td>\n",
       "      <td>57.703845</td>\n",
       "      <td>16.307608</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 5</td>\n",
       "      <td>Male</td>\n",
       "      <td>4304</td>\n",
       "      <td></td>\n",
       "      <td>0.116171</td>\n",
       "      <td>29.623606</td>\n",
       "      <td>57.109665</td>\n",
       "      <td>13.150558</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 5</td>\n",
       "      <td>Female</td>\n",
       "      <td>3943</td>\n",
       "      <td></td>\n",
       "      <td>0.177530</td>\n",
       "      <td>26.249049</td>\n",
       "      <td>56.632006</td>\n",
       "      <td>16.941415</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 6</td>\n",
       "      <td>Male</td>\n",
       "      <td>4353</td>\n",
       "      <td></td>\n",
       "      <td>0.022973</td>\n",
       "      <td>29.565817</td>\n",
       "      <td>57.293820</td>\n",
       "      <td>13.117390</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 6</td>\n",
       "      <td>Female</td>\n",
       "      <td>4004</td>\n",
       "      <td></td>\n",
       "      <td>0.000000</td>\n",
       "      <td>26.123876</td>\n",
       "      <td>58.591409</td>\n",
       "      <td>15.284715</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 7</td>\n",
       "      <td>Male</td>\n",
       "      <td>4308</td>\n",
       "      <td>0</td>\n",
       "      <td>0.116063</td>\n",
       "      <td>28.667595</td>\n",
       "      <td>59.261838</td>\n",
       "      <td>11.954503</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 7</td>\n",
       "      <td>Female</td>\n",
       "      <td>4034</td>\n",
       "      <td>0.0247893</td>\n",
       "      <td>0.123946</td>\n",
       "      <td>26.648488</td>\n",
       "      <td>57.858205</td>\n",
       "      <td>15.344571</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 8</td>\n",
       "      <td>Male</td>\n",
       "      <td>4337</td>\n",
       "      <td>0.0230574</td>\n",
       "      <td>0.138344</td>\n",
       "      <td>27.784183</td>\n",
       "      <td>59.810929</td>\n",
       "      <td>12.243486</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 8</td>\n",
       "      <td>Female</td>\n",
       "      <td>4032</td>\n",
       "      <td>0</td>\n",
       "      <td>0.099206</td>\n",
       "      <td>25.173611</td>\n",
       "      <td>60.193452</td>\n",
       "      <td>14.533730</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 9</td>\n",
       "      <td>Male</td>\n",
       "      <td>4493</td>\n",
       "      <td>0.0222568</td>\n",
       "      <td>0.044514</td>\n",
       "      <td>27.398175</td>\n",
       "      <td>58.468729</td>\n",
       "      <td>14.066325</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 9</td>\n",
       "      <td>Female</td>\n",
       "      <td>4084</td>\n",
       "      <td>0</td>\n",
       "      <td>0.122429</td>\n",
       "      <td>23.849167</td>\n",
       "      <td>60.259549</td>\n",
       "      <td>15.768854</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 10</td>\n",
       "      <td>Male</td>\n",
       "      <td>4516</td>\n",
       "      <td></td>\n",
       "      <td>0.066430</td>\n",
       "      <td>25.575731</td>\n",
       "      <td>60.540301</td>\n",
       "      <td>13.817538</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 10</td>\n",
       "      <td>Female</td>\n",
       "      <td>4149</td>\n",
       "      <td></td>\n",
       "      <td>0.024102</td>\n",
       "      <td>24.536033</td>\n",
       "      <td>58.640636</td>\n",
       "      <td>16.799229</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 11</td>\n",
       "      <td>Male</td>\n",
       "      <td>5859</td>\n",
       "      <td>0.0170678</td>\n",
       "      <td>0.119474</td>\n",
       "      <td>25.857655</td>\n",
       "      <td>59.122717</td>\n",
       "      <td>14.883086</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <td>Wave 11</td>\n",
       "      <td>Female</td>\n",
       "      <td>5375</td>\n",
       "      <td>0.0372093</td>\n",
       "      <td>0.037209</td>\n",
       "      <td>24.037209</td>\n",
       "      <td>58.623256</td>\n",
       "      <td>17.265116</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "            Sex  Total Employed [-4] Refused/Not stated  [-3] Dont know  \\\n",
       "Wave 1     Male            4549               0.0219829        0.285777   \n",
       "Wave 1   Female            3976               0.0754527        0.301811   \n",
       "Wave 2     Male            4325                                0.138728   \n",
       "Wave 2   Female            3763                                0.186022   \n",
       "Wave 3     Male            4247                                0.211914   \n",
       "Wave 3   Female            3744                                0.293803   \n",
       "Wave 4     Male            4155               0.0240674        0.264741   \n",
       "Wave 4   Female            3667                       0        0.054540   \n",
       "Wave 5     Male            4304                                0.116171   \n",
       "Wave 5   Female            3943                                0.177530   \n",
       "Wave 6     Male            4353                                0.022973   \n",
       "Wave 6   Female            4004                                0.000000   \n",
       "Wave 7     Male            4308                       0        0.116063   \n",
       "Wave 7   Female            4034               0.0247893        0.123946   \n",
       "Wave 8     Male            4337               0.0230574        0.138344   \n",
       "Wave 8   Female            4032                       0        0.099206   \n",
       "Wave 9     Male            4493               0.0222568        0.044514   \n",
       "Wave 9   Female            4084                       0        0.122429   \n",
       "Wave 10    Male            4516                                0.066430   \n",
       "Wave 10  Female            4149                                0.024102   \n",
       "Wave 11    Male            5859               0.0170678        0.119474   \n",
       "Wave 11  Female            5375               0.0372093        0.037209   \n",
       "\n",
       "         [1] Fewer hours  [2] About the same  [3] More hours  \n",
       "Wave 1         30.160475           54.297648       15.234117  \n",
       "Wave 1         26.685111           55.709256       17.228370  \n",
       "Wave 2         31.283237           53.502890       15.075145  \n",
       "Wave 2         24.608026           57.560457       17.645496  \n",
       "Wave 3         31.316223           54.744526       13.727337  \n",
       "Wave 3         25.240385           57.104701       17.361111  \n",
       "Wave 4         30.878460           55.547533       13.285199  \n",
       "Wave 4         25.934006           57.703845       16.307608  \n",
       "Wave 5         29.623606           57.109665       13.150558  \n",
       "Wave 5         26.249049           56.632006       16.941415  \n",
       "Wave 6         29.565817           57.293820       13.117390  \n",
       "Wave 6         26.123876           58.591409       15.284715  \n",
       "Wave 7         28.667595           59.261838       11.954503  \n",
       "Wave 7         26.648488           57.858205       15.344571  \n",
       "Wave 8         27.784183           59.810929       12.243486  \n",
       "Wave 8         25.173611           60.193452       14.533730  \n",
       "Wave 9         27.398175           58.468729       14.066325  \n",
       "Wave 9         23.849167           60.259549       15.768854  \n",
       "Wave 10        25.575731           60.540301       13.817538  \n",
       "Wave 10        24.536033           58.640636       16.799229  \n",
       "Wave 11        25.857655           59.122717       14.883086  \n",
       "Wave 11        24.037209           58.623256       17.265116  "
      ]
     },
     "execution_count": 326,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "final_table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
